# HTTP ä»£ç†ç«¯å£
port: 7890 

# SOCKS5 ä»£ç†ç«¯å£
socks-port: 7891 

# Linux å’Œ macOS çš„ redir ä»£ç†ç«¯å£
redir-port: 7892 

# å…è®¸å±€åŸŸç½‘çš„è¿æ¥
allow-lan: true

# è§„åˆ™æ¨¡å¼ï¼šRuleï¼ˆè§„åˆ™ï¼‰ / Globalï¼ˆå…¨å±€ä»£ç†ï¼‰/ Directï¼ˆå…¨å±€ç›´è¿ï¼‰
mode: rule

# è®¾ç½®æ—¥å¿—è¾“å‡ºçº§åˆ« (é»˜è®¤çº§åˆ«ï¼šsilentï¼Œå³ä¸è¾“å‡ºä»»ä½•å†…å®¹ï¼Œä»¥é¿å…å› æ—¥å¿—å†…å®¹è¿‡å¤§è€Œå¯¼è‡´ç¨‹åºå†…å­˜æº¢å‡ºï¼‰ã€‚
# 5 ä¸ªçº§åˆ«ï¼šsilent / info / warning / error / debugã€‚çº§åˆ«è¶Šé«˜æ—¥å¿—è¾“å‡ºé‡è¶Šå¤§ï¼Œè¶Šå€¾å‘äºè°ƒè¯•ï¼Œè‹¥éœ€è¦è¯·è‡ªè¡Œå¼€å¯ã€‚
log-level: silent
# Clash çš„ RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API çš„å£ä»¤
secret: 'b&ZlKTte5OnEt2Sn'

# æ‚¨å¯ä»¥å°†é™æ€ç½‘é¡µèµ„æºï¼ˆå¦‚ clash-dashboardï¼‰æ”¾ç½®åœ¨ä¸€ä¸ªç›®å½•ä¸­ï¼Œclash å°†ä¼šæœåŠ¡äº `RESTful API/ui`
# å‚æ•°åº”å¡«å†™é…ç½®ç›®å½•çš„ç›¸å¯¹è·¯å¾„æˆ–ç»å¯¹è·¯å¾„ã€‚
# external-ui: /code/clash-dashboard

proxies:
- name: ç¾å›½è¥¿é›…å›¾
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 70a7a604-t855s0-t92jan-1m0zr.se.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ç¾å›½è¥¿é›…å›¾2
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: ce2f24ed-t855s0-t92jan-1m0zr.sv.plebai.net
  tls: true
  type: socks5
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ç¾å›½æ´›æ‰çŸ¶[CU]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 15229
  server: ed09003e-t855s0-t92jan-1m0zr.cu.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ç¾å›½ç¡…è°·
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 3b2cef7c-t855s0-t92jan-1m0zr.sj.gotochinatown.net
  tls: true
  type: socks5
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ç¾å›½ç¡…è°·2
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 8b2199f3-t855s0-t92jan-1m0zr.sj.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ç¾å›½åœ£ä½•å¡
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: b3bc6290-t855s0-t92jan-1m0zr.sjc.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ç¾å›½æ´›æ‰çŸ¶
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 08461c51-t855s0-t92jan-1m0zr.los.gotochinatown.net
  tls: true
  type: socks5
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ç¾å›½æ´›æ‰çŸ¶2
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 08461c51-t855s0-t92jan-1m0zr.los.gotochinatown.net
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 5228
  server: 7a58cdbd-t855s0-t92jan-1m0zr.cm4.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 1eec4401-t855s0-t92jan-1m0zr.hkt2.cdnhuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  password: <password>
  port: 8443
  server: 7e5e251a-t855s0-t92jan-1m0zr.hkt.cdnhuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- alterId: 2
  cipher: auto
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  network: ws
  port: 80
  server: bbcaa89e-t855s0-t92jan-1m0zr.hkt.gotochinatown.net
  tls: false
  type: vmess
  uuid: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
  ws-path: /
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  password: <password>
  port: 443
  server: 1eec4401-t855s0-t92jan-1m0zr.hkt2.cdnhuawei.com
  tls: true
  type: socks5
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¬ğŸ‡§ è‹±å›½
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: e910b848-t855s0-t92jan-1m0zr.uk.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡«ğŸ‡· æ³•å›½
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 266d56cb-t855s0-t92jan-1m0zr.fr.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡©ğŸ‡ª å¾·å›½
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: e3ba4848-t855s0-t92jan-1m0zr.de.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš[CM]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 31233
  server: daa940e7-t855s0-t92jan-1m0zr.my.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¹ğŸ‡­ æ³°å›½[CM]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 32232
  server: 0e9b5e75-t855s0-t92jan-1m0zr.id.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡°ğŸ‡·éŸ©åœ‹[CT]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 31433
  server: f8c2bdcb-t855s0-t92jan-1m0zr.kr.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¨ğŸ‡³ å°æ¹¾
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: eecb35ab-t855s0-t92jan-1m0zr.tw3.p5pv.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 577aecda-t855s0-t92jan-1m0zr.jp.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡®ğŸ‡© å°å°¼[CM]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 32233
  server: 0e9b5e75-t855s0-t92jan-1m0zr.id.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬[CM]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 27233
  server: 7a58cdbd-t855s0-t92jan-1m0zr.cm4.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 991a3925-t855s0-t92jan-1m0zr.jp4.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡[CM]
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 17235
  server: 7a58cdbd-t855s0-t92jan-1m0zr.cm4.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: e6fa5556-t855s0-t92jan-1m0zr.sg.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  password: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
  port: 443
  server: 3da97beb-t855s0-t92jan-1m0zr.sg3.oshuawei.com
  tls: true
  type: http
  username: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
- alterId: 0
  cipher: auto
  name: çº¿è·¯å°‘è¯·æ›´æ¢è½¯ä»¶çœ‹å…¬å‘Š
  network: tcp
  port: 443
  server: hostloc.com
  tls: true
  type: vmess
  uuid: 6d2bfb11-90b6-11ed-8de5-f23c91cfbbc9
proxy-groups:
- name: Ghelper
  proxies:
  - ğŸŒ å…¨çƒæ™ºèƒ½
  - ç¾å›½è¥¿é›…å›¾
  - ç¾å›½è¥¿é›…å›¾2
  - ç¾å›½æ´›æ‰çŸ¶[CU]
  - ç¾å›½ç¡…è°·
  - ç¾å›½ç¡…è°·2
  - ç¾å›½åœ£ä½•å¡
  - ç¾å›½æ´›æ‰çŸ¶
  - ç¾å›½æ´›æ‰çŸ¶2
  - ğŸ‡­ğŸ‡° é¦™æ¸¯æ™ºèƒ½
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  - ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  - ğŸ‡¬ğŸ‡§ è‹±å›½
  - ğŸ‡«ğŸ‡· æ³•å›½
  - ğŸ‡©ğŸ‡ª å¾·å›½
  - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš[CM]
  - ğŸ‡¹ğŸ‡­ æ³°å›½[CM]
  - ğŸ‡°ğŸ‡·éŸ©åœ‹[CT]
  - ğŸ‡¨ğŸ‡³ å°æ¹¾
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  - ğŸ‡®ğŸ‡© å°å°¼[CM]
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬[CM]
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡[CM]
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  - AIä¸“ç”¨
  - çº¿è·¯å°‘è¯·æ›´æ¢è½¯ä»¶çœ‹å…¬å‘Š
  type: select
- interval: 7200
  name: ğŸŒ å…¨çƒæ™ºèƒ½
  proxies:
  - ç¾å›½è¥¿é›…å›¾
  - ç¾å›½è¥¿é›…å›¾2
  - ç¾å›½æ´›æ‰çŸ¶[CU]
  - ç¾å›½ç¡…è°·
  - ç¾å›½ç¡…è°·2
  - ç¾å›½åœ£ä½•å¡
  - ç¾å›½æ´›æ‰çŸ¶
  - ç¾å›½æ´›æ‰çŸ¶2
  - ğŸ‡­ğŸ‡° é¦™æ¸¯æ™ºèƒ½
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  - ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  - ğŸ‡¬ğŸ‡§ è‹±å›½
  - ğŸ‡«ğŸ‡· æ³•å›½
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  - çº¿è·¯å°‘è¯·æ›´æ¢è½¯ä»¶çœ‹å…¬å‘Š
  type: url-test
  url: http://www.gstatic.com/generate_204
- interval: 7200
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯æ™ºèƒ½
  proxies:
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  - ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  type: url-test
  url: http://www.gstatic.com/generate_204
- interval: 7200
  name: AIä¸“ç”¨
  proxies:
  - ç¾å›½è¥¿é›…å›¾
  - ç¾å›½è¥¿é›…å›¾2
  - ç¾å›½æ´›æ‰çŸ¶[CU]
  - ç¾å›½ç¡…è°·
  - ç¾å›½ç¡…è°·2
  - ç¾å›½åœ£ä½•å¡
  - ç¾å›½æ´›æ‰çŸ¶
  - ç¾å›½æ´›æ‰çŸ¶2
  - ğŸ‡¬ğŸ‡§ è‹±å›½
  - ğŸ‡«ğŸ‡· æ³•å›½
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬[CM]
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡[CM]
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,ip-api.com,DIRECT
- DOMAIN-SUFFIX,ipip.net,DIRECT
- DOMAIN-SUFFIX,ip138.com,DIRECT
- DOMAIN-SUFFIX,skype.com,DIRECT
- DOMAIN-SUFFIX,skype.comedge.skype.net,DIRECT
- DOMAIN-SUFFIX,skypeassets.com,DIRECT
- DOMAIN-SUFFIX,skypeforbusiness.com,DIRECT
- DOMAIN-SUFFIX,cdnkuaisou.com,DIRECT
- DOMAIN-SUFFIX,cnkuaishou.com,DIRECT
- DOMAIN-SUFFIX,cmhuawei.com,DIRECT
- DOMAIN-SUFFIX,cmhuawei.com,DIRECT
- DOMAIN-SUFFIX,cdnhuawei.com,DIRECT
- DOMAIN-SUFFIX,viphuawei.com,DIRECT
- DOMAIN-SUFFIX,chromeapi.com,DIRECT
- DOMAIN-SUFFIX,paypal.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,airwallex.com,DIRECT
- DOMAIN-SUFFIX,stripe.com,DIRECT
- DOMAIN-SUFFIX,wooshpay.com,DIRECT
- DOMAIN-SUFFIX,payssion.com,DIRECT
- DOMAIN-SUFFIX,chrapi.com,DIRECT
- DOMAIN-SUFFIX,firapi.com,DIRECT
- DOMAIN-SUFFIX,gheapi.com,DIRECT
- DOMAIN-SUFFIX,broapi.com,DIRECT
- DOMAIN-SUFFIX,edgapi.com,DIRECT
- DOMAIN-SUFFIX,browserapi.net,DIRECT
- DOMAIN-SUFFIX,cnsync.com,DIRECT
- DOMAIN-SUFFIX,on1t.com,DIRECT
- DOMAIN-SUFFIX,chromeapi.net,DIRECT
- DOMAIN-SUFFIX,copydesign.net,DIRECT
- DOMAIN-SUFFIX,jy3p.com,DIRECT
- DOMAIN-SUFFIX,p5pv.com,DIRECT
- DOMAIN-SUFFIX,z7zi.com,DIRECT
- DOMAIN-SUFFIX,j2ai.com,DIRECT
- DOMAIN-SUFFIX,alrihla.net,DIRECT
- DOMAIN-SUFFIX,sphinxsearch.net,DIRECT
- DOMAIN-SUFFIX,skype.com,DIRECT
- DOMAIN-SUFFIX,cdnhuawei.com,DIRECT
- DOMAIN-SUFFIX,cdnkuaishou.com,DIRECT
- DOMAIN-SUFFIX,chromeapi.net,DIRECT
- DOMAIN-KEYWORD,google,Ghelper
- DOMAIN-SUFFIX,ggpht.com,Ghelper
- DOMAIN-SUFFIX,gmail.com,Ghelper
- DOMAIN-SUFFIX,gvt2.com,Ghelper
- DOMAIN-SUFFIX,gvt3.com,Ghelper
- DOMAIN-SUFFIX,chrome.com,Ghelper
- DOMAIN-SUFFIX,wikipedia.org,Ghelper
- DOMAIN-SUFFIX,wikimedia.org,Ghelper
- DOMAIN-SUFFIX,appspot.com,Ghelper
- DOMAIN-SUFFIX,android.com,Ghelper
- DOMAIN-SUFFIX,github.com,Ghelper
- DOMAIN-SUFFIX,gitbook.com,Ghelper
- DOMAIN-SUFFIX,kaggle.com,Ghelper
- DOMAIN-SUFFIX,arxiv.org,Ghelper
- DOMAIN-SUFFIX,wiktionary.org,Ghelper
- DOMAIN-SUFFIX,blogger.com,Ghelper
- DOMAIN-KEYWORD,google,Ghelper
- DOMAIN-KEYWORD,youtube,Ghelper
- DOMAIN-SUFFIX,ggpht.com,Ghelper
- DOMAIN-SUFFIX,gmail.com,Ghelper
- DOMAIN-SUFFIX,gvt2.com,Ghelper
- DOMAIN-SUFFIX,gvt3.com,Ghelper
- DOMAIN-SUFFIX,chrome.com,Ghelper
- DOMAIN-SUFFIX,wikipedia.org,Ghelper
- DOMAIN-SUFFIX,wikimedia.org,Ghelper
- DOMAIN-SUFFIX,appspot.com,Ghelper
- DOMAIN-SUFFIX,android.com,Ghelper
- DOMAIN-SUFFIX,github.com,Ghelper
- DOMAIN-SUFFIX,gitbook.com,Ghelper
- DOMAIN-SUFFIX,kaggle.com,Ghelper
- DOMAIN-SUFFIX,arxiv.org,Ghelper
- DOMAIN-SUFFIX,wiktionary.org,Ghelper
- DOMAIN-SUFFIX,blogger.com,Ghelper
- DOMAIN-SUFFIX,youtu.be,Ghelper
- DOMAIN-SUFFIX,ytimg.com,Ghelper
- DOMAIN-SUFFIX,youtube.com,Ghelper
- DOMAIN-SUFFIX,instagram.com,Ghelper
- DOMAIN-SUFFIX,twitter.com,Ghelper
- DOMAIN-SUFFIX,t.co,Ghelper
- DOMAIN-SUFFIX,facebook.com,Ghelper
- DOMAIN-SUFFIX,telegram.org,Ghelper
- DOMAIN-SUFFIX,whatsapp.com,Ghelper
- DOMAIN-SUFFIX,whatsapp.net,Ghelper
- DOMAIN-SUFFIX,linkedin.com,Ghelper
- DOMAIN-SUFFIX,licdn.com,Ghelper
- DOMAIN-SUFFIX,trkn.us,Ghelper
- DOMAIN-SUFFIX,cedexis.com,Ghelper
- DOMAIN-SUFFIX,ip.sb,Ghelper
- DOMAIN-SUFFIX,ip.net,Ghelper
- DOMAIN-SUFFIX,openai.com,Ghelper
- DOMAIN-SUFFIX,auth0.com,Ghelper
- DOMAIN-SUFFIX,featuregates.org,Ghelper
- DOMAIN-SUFFIX,statsigapi.net,Ghelper
- DOMAIN-SUFFIX,intercom.io,Ghelper
- DOMAIN-SUFFIX,intercomcdn.com,Ghelper
- DOMAIN-SUFFIX,sentry.io,Ghelper
- DOMAIN-SUFFIX,sentry.dev,Ghelper
- DOMAIN-SUFFIX,oaistatic.com,Ghelper
- DOMAIN-SUFFIX,oaiusercontent.com,Ghelper
- DOMAIN-SUFFIX,chatgpt.com,Ghelper
- DOMAIN-SUFFIX,chatgpt-async-webps-prod-southcentralus-6.webpubsub.azure.com,Ghelper
- DOMAIN-SUFFIX,claude.ai,Ghelper
- DOMAIN-SUFFIX,anthropic.com,Ghelper
- DOMAIN-SUFFIX,intercomcdn.com,Ghelper
- DOMAIN-SUFFIX,intercom.io,Ghelper
- DOMAIN-SUFFIX,bing.com,Ghelper
- DOMAIN-SUFFIX,microsoftonline.com,Ghelper
- DOMAIN-SUFFIX,live.com,Ghelper
- DOMAIN-SUFFIX,msecnd.net,Ghelper
- DOMAIN-SUFFIX,msn.com,Ghelper
- DOMAIN-SUFFIX,bingapis.com,Ghelper
- DOMAIN-SUFFIX,bing.net,Ghelper
- DOMAIN-SUFFIX,windows.com,Ghelper
- DOMAIN-SUFFIX,microsoft.com,Ghelper
- DOMAIN-SUFFIX,linkedin.com,Ghelper
- DOMAIN-SUFFIX,licdn.com,Ghelper
- DOMAIN-SUFFIX,trkn.us,Ghelper
- DOMAIN-SUFFIX,cedexis.com,Ghelper
- GEOIP,CN,DIRECT
- MATCH, Ghelper
